blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://feedback.cometchat.com
    about: Suggest an idea or a feature for this project
  - name: Community Forums
    url: https://forum.cometchat.com
    about: Discuss this in the CometChat Pro Community Forums
  - name: Documentation
    url: https://prodocs.cometchat.com
    about: Read the documentation
